# Generated by Django 5.2.7 on 2025-10-30 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccuralType',
            fields=[
                ('accural_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('accural_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accural_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus_type_name', models.CharField(max_length=100)),
                ('bonus_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'bonus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_workers', models.IntegerField()),
                ('monthly_budget', models.IntegerField()),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=45)),
                ('bank_account', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('sum', models.FloatField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('payment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_monthly_wage', models.FloatField()),
                ('position_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherAccurals',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='repository_app.employee')),
                ('total_sum', models.FloatField()),
            ],
            options={
                'db_table': 'other_accurals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='repository_app.employee')),
                ('other_accurals', models.IntegerField()),
                ('total_sum', models.FloatField()),
            ],
            options={
                'db_table': 'wage',
                'managed': False,
            },
        ),
    ]
